// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcc4Jegrzp44s0UEs3e_9NmxIgOdl4HiE',
    appId: '1:923678737184:web:5b629dccefa5dd16568d45',
    messagingSenderId: '923678737184',
    projectId: 'succinct-c0b2c',
    authDomain: 'succinct-c0b2c.firebaseapp.com',
    storageBucket: 'succinct-c0b2c.firebasestorage.app',
    measurementId: 'G-700HV5MZQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KqCEvzfphSp9IJnoCwZ2wc9yE2EuCao',
    appId: '1:923678737184:android:39254dde6cb58a67568d45',
    messagingSenderId: '923678737184',
    projectId: 'succinct-c0b2c',
    storageBucket: 'succinct-c0b2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2qyfXKBLPjD9L3YffQqrXB2W-vlAKdls',
    appId: '1:923678737184:ios:9eecd36893f959a5568d45',
    messagingSenderId: '923678737184',
    projectId: 'succinct-c0b2c',
    storageBucket: 'succinct-c0b2c.firebasestorage.app',
    iosBundleId: 'com.example.succinct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2qyfXKBLPjD9L3YffQqrXB2W-vlAKdls',
    appId: '1:923678737184:ios:9eecd36893f959a5568d45',
    messagingSenderId: '923678737184',
    projectId: 'succinct-c0b2c',
    storageBucket: 'succinct-c0b2c.firebasestorage.app',
    iosBundleId: 'com.example.succinct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcc4Jegrzp44s0UEs3e_9NmxIgOdl4HiE',
    appId: '1:923678737184:web:08dfe1d24eaae5d1568d45',
    messagingSenderId: '923678737184',
    projectId: 'succinct-c0b2c',
    authDomain: 'succinct-c0b2c.firebaseapp.com',
    storageBucket: 'succinct-c0b2c.firebasestorage.app',
    measurementId: 'G-P0Q7ZMFTWN',
  );

}